# Dependabot configuration for myTraderGEO
# Automatically creates PRs to update dependencies

version: 2

updates:
  # Backend .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "mardantas"
    assignees:
      - "mardantas"
    labels:
      - "dependencies"
      - "tech:backend"
      - "agent:DE"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major versions during Discovery/MVP phase
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "mardantas"
    assignees:
      - "mardantas"
    labels:
      - "dependencies"
      - "tech:frontend"
      - "agent:FE"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major versions during Discovery/MVP phase
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group minor and patch updates together
    groups:
      vue-ecosystem:
        patterns:
          - "vue"
          - "vue-*"
          - "@vue/*"
          - "pinia"
          - "vue-router"
      vite-ecosystem:
        patterns:
          - "vite"
          - "vite-*"
          - "@vitejs/*"
      testing-tools:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "@playwright/*"
          - "@vue/test-utils"
      dev-tools:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "prettier"
          - "typescript"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/05-infra/dockerfiles/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "mardantas"
    assignees:
      - "mardantas"
    labels:
      - "dependencies"
      - "tech:infra"
      - "agent:PE"
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: "docker"
    directory: "/05-infra/dockerfiles/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "mardantas"
    assignees:
      - "mardantas"
    labels:
      - "dependencies"
      - "tech:infra"
      - "agent:PE"
    commit-message:
      prefix: "chore(docker)"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "mardantas"
    assignees:
      - "mardantas"
    labels:
      - "dependencies"
      - "tech:infra"
      - "agent:GM"
    commit-message:
      prefix: "chore(ci)"
