#!/bin/bash
#
# [PROJECT_NAME] Server Setup - Master Script
# Generated by PE Agent from template
# Version: 1.0
#
# This script orchestrates all 9 server hardening steps for a production-ready VPS.
# It should be run on a fresh Debian 12 installation.
#
# Usage:
#   sudo bash server-setup.sh --environment <staging|production>
#
# Prerequisites:
#   - Fresh Debian 12 VPS
#   - Root or sudo access
#   - Internet connectivity
#
# What this script does:
#   Step 0: Configure hostname
#   Step 1: System update and essential tools
#   Step 2: Docker Engine installation
#   Step 3: UFW firewall setup
#   Step 4: Security hardening (fail2ban, chrony, htpasswd)
#   Step 5: Project user and group creation
#   Step 6: SSH keys configuration
#   Step 7: Directory structure creation
#   Step 8: Environment file (.env) template
#   Step 9: Verification and validation
#

set -e  # Exit on error
set -u  # Exit on undefined variable

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Project configuration (customized by PE Agent)
PROJECT_NAME="[PROJECT_NAME]"
PROJECT_USER="[PROJECT_USER]"
PROJECT_GROUP="[PROJECT_GROUP]"
STAGING_HOSTNAME="[STAGING_HOSTNAME]"
PROD_HOSTNAME="[PROD_HOSTNAME]"
TIMEZONE="[TIMEZONE]"

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_DIR="${SCRIPT_DIR}/setup"

# Log file
LOG_FILE="/var/log/${PROJECT_NAME}-server-setup.log"

#######################################
# Helper Functions
#######################################

log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR:${NC} $1" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING:${NC} $1" | tee -a "$LOG_FILE"
}

log_info() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')] INFO:${NC} $1" | tee -a "$LOG_FILE"
}

separator() {
    echo "" | tee -a "$LOG_FILE"
    echo "========================================" | tee -a "$LOG_FILE"
    echo "" | tee -a "$LOG_FILE"
}

confirm() {
    local message="$1"
    local response

    while true; do
        read -p "$(echo -e ${YELLOW}${message}${NC}) [y/N]: " response
        case "$response" in
            [yY][eE][sS]|[yY])
                return 0
                ;;
            [nN][oO]|[nN]|"")
                return 1
                ;;
            *)
                echo "Please answer yes or no."
                ;;
        esac
    done
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root or with sudo"
        exit 1
    fi
}

check_os() {
    if [[ ! -f /etc/os-release ]]; then
        log_error "Cannot detect OS version"
        exit 1
    fi

    . /etc/os-release

    if [[ "$ID" != "debian" ]]; then
        log_error "This script is designed for Debian 12. Detected: $ID"
        exit 1
    fi

    if [[ "$VERSION_ID" != "12" ]]; then
        log_warning "This script is optimized for Debian 12. Detected version: $VERSION_ID"
        if ! confirm "Continue anyway?"; then
            exit 1
        fi
    fi
}

#######################################
# Main Script
#######################################

main() {
    # Parse arguments
    ENVIRONMENT=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --environment|-e)
                ENVIRONMENT="$2"
                shift 2
                ;;
            --help|-h)
                echo "Usage: sudo bash server-setup.sh --environment <staging|production>"
                echo ""
                echo "Options:"
                echo "  --environment, -e    Environment (staging or production)"
                echo "  --help, -h           Show this help message"
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                echo "Use --help for usage information"
                exit 1
                ;;
        esac
    done

    # Validate environment
    if [[ -z "$ENVIRONMENT" ]]; then
        log_error "Environment not specified. Use --environment staging or --environment production"
        exit 1
    fi

    if [[ "$ENVIRONMENT" != "staging" && "$ENVIRONMENT" != "production" ]]; then
        log_error "Invalid environment: $ENVIRONMENT. Must be 'staging' or 'production'"
        exit 1
    fi

    # Set hostname based on environment
    if [[ "$ENVIRONMENT" == "staging" ]]; then
        TARGET_HOSTNAME="$STAGING_HOSTNAME"
    else
        TARGET_HOSTNAME="$PROD_HOSTNAME"
    fi

    # Pre-flight checks
    check_root
    check_os

    # Banner
    clear
    separator
    log "🚀 ${PROJECT_NAME} Server Setup"
    log ""
    log "   Environment: ${ENVIRONMENT}"
    log "   Target Hostname: ${TARGET_HOSTNAME}"
    log "   Project User: ${PROJECT_USER}"
    log "   Timezone: ${TIMEZONE}"
    log ""
    log "   This script will execute 9 hardening steps:"
    log "   [0] Configure hostname"
    log "   [1] System update and tools"
    log "   [2] Docker Engine installation"
    log "   [3] UFW firewall setup"
    log "   [4] Security hardening (fail2ban, chrony)"
    log "   [5] User and group creation"
    log "   [6] SSH keys configuration"
    log "   [7] Directory structure"
    log "   [8] Environment file (.env)"
    log "   [9] Verification"
    separator

    log_warning "⚠️  This will modify system configuration!"
    log_warning "⚠️  Make sure you have a backup if this is not a fresh installation."
    separator

    if ! confirm "Proceed with server setup?"; then
        log "Setup cancelled by user"
        exit 0
    fi

    # Start setup
    log ""
    log "Starting server setup at $(date)"
    separator

    # Step 0: Hostname
    log "📝 Step 0: Configure Hostname"
    if [[ -f "${SETUP_DIR}/00-hostname.sh" ]]; then
        bash "${SETUP_DIR}/00-hostname.sh" "$TARGET_HOSTNAME" || {
            log_error "Step 0 failed"
            exit 1
        }
        log "✅ Step 0 completed"
    else
        log_warning "Step 0 script not found, skipping"
    fi
    separator

    # Step 1: System Update
    log "📝 Step 1: System Update and Tools"
    if [[ -f "${SETUP_DIR}/01-system-update.sh" ]]; then
        bash "${SETUP_DIR}/01-system-update.sh" || {
            log_error "Step 1 failed"
            exit 1
        }
        log "✅ Step 1 completed"
    else
        log_warning "Step 1 script not found, skipping"
    fi
    separator

    # Step 2: Docker
    log "📝 Step 2: Docker Engine Installation"
    if [[ -f "${SETUP_DIR}/02-docker.sh" ]]; then
        bash "${SETUP_DIR}/02-docker.sh" || {
            log_error "Step 2 failed"
            exit 1
        }
        log "✅ Step 2 completed"
    else
        log_warning "Step 2 script not found, skipping"
    fi
    separator

    # Step 3: Firewall
    log "📝 Step 3: UFW Firewall Setup"
    if [[ -f "${SETUP_DIR}/03-firewall.sh" ]]; then
        bash "${SETUP_DIR}/03-firewall.sh" || {
            log_error "Step 3 failed"
            exit 1
        }
        log "✅ Step 3 completed"
    else
        log_warning "Step 3 script not found, skipping"
    fi
    separator

    # Step 4: Security
    log "📝 Step 4: Security Hardening"
    if [[ -f "${SETUP_DIR}/04-security.sh" ]]; then
        bash "${SETUP_DIR}/04-security.sh" "$TIMEZONE" || {
            log_error "Step 4 failed"
            exit 1
        }
        log "✅ Step 4 completed"
    else
        log_warning "Step 4 script not found, skipping"
    fi
    separator

    # Step 5: User
    log "📝 Step 5: User and Group Creation"
    if [[ -f "${SETUP_DIR}/05-user.sh" ]]; then
        bash "${SETUP_DIR}/05-user.sh" "$PROJECT_USER" "$PROJECT_GROUP" || {
            log_error "Step 5 failed"
            exit 1
        }
        log "✅ Step 5 completed"
    else
        log_warning "Step 5 script not found, skipping"
    fi
    separator

    # Step 6: SSH Keys
    log "📝 Step 6: SSH Keys Configuration"
    if [[ -f "${SETUP_DIR}/06-ssh-keys.sh" ]]; then
        bash "${SETUP_DIR}/06-ssh-keys.sh" "$PROJECT_USER" || {
            log_error "Step 6 failed"
            exit 1
        }
        log "✅ Step 6 completed"
    else
        log_warning "Step 6 script not found, skipping"
    fi
    separator

    # Step 7: Directories
    log "📝 Step 7: Directory Structure Creation"
    if [[ -f "${SETUP_DIR}/07-directories.sh" ]]; then
        bash "${SETUP_DIR}/07-directories.sh" "$PROJECT_USER" "$PROJECT_NAME" || {
            log_error "Step 7 failed"
            exit 1
        }
        log "✅ Step 7 completed"
    else
        log_warning "Step 7 script not found, skipping"
    fi
    separator

    # Step 8: .env
    log "📝 Step 8: Environment File (.env) Template"
    if [[ -f "${SETUP_DIR}/08-env.sh" ]]; then
        bash "${SETUP_DIR}/08-env.sh" "$PROJECT_USER" "$PROJECT_NAME" "$ENVIRONMENT" || {
            log_error "Step 8 failed"
            exit 1
        }
        log "✅ Step 8 completed"
    else
        log_warning "Step 8 script not found, skipping"
    fi
    separator

    # Step 9: Verification
    log "📝 Step 9: Verification and Validation"
    if [[ -f "${SETUP_DIR}/09-verify.sh" ]]; then
        bash "${SETUP_DIR}/09-verify.sh" "$PROJECT_USER" || {
            log_error "Step 9 failed"
            exit 1
        }
        log "✅ Step 9 completed"
    else
        log_warning "Step 9 script not found, skipping"
    fi
    separator

    # Success
    log "🎉 Server setup completed successfully!"
    log ""
    log "   Next steps:"
    log "   1. Review the .env file in /home/${PROJECT_USER}/${PROJECT_NAME}/.env.${ENVIRONMENT}"
    log "   2. Add your SSH public key to /home/${PROJECT_USER}/.ssh/authorized_keys"
    log "   3. Test SSH connection: ssh ${PROJECT_USER}@${TARGET_HOSTNAME}"
    log "   4. Deploy your application using: bash deploy.sh ${ENVIRONMENT}"
    log ""
    log "   Log file: ${LOG_FILE}"
    separator

    log "Setup finished at $(date)"
}

# Run main function
main "$@"
