name: 📋 Épico
description: Criar um novo épico para o projeto
title: "[ÉPICO] "
labels: ["epic", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 ÉPICO - Template DDD
        Use este template para criar épicos seguindo os padrões DDD estabelecidos.
        
  - type: input
    id: epic-name
    attributes:
      label: Nome do Épico (em português)
      description: Nome descritivo do épico usando Linguagem Ubíqua
      placeholder: ex. Gestão de Pedidos, Gestão de Estoque
    validations:
      required: true
      
  - type: input
    id: bounded-context
    attributes:
      label: Bounded Context
      description: Em qual Contexto Delimitado este épico se enquadra?
      placeholder: ex. Contexto de Gestão de Pedidos
    validations:
      required: true
      
  - type: input
    id: subdomain
    attributes:
      label: Subdomínio
      description: Qual subdomínio do negócio este épico representa?
      placeholder: ex. Processamento de Pedidos
    validations:
      required: true
      
  - type: dropdown
    id: domain-type
    attributes:
      label: Tipo de Subdomínio
      description: Qual tipo de subdomínio este épico pertence?
      options:
        - Core (Domínio Principal)
        - Supporting (Domínio de Suporte)
        - Generic (Domínio Genérico)
    validations:
      required: true
      
  - type: textarea
    id: ubiquitous-language
    attributes:
      label: Linguagem Ubíqua
      description: Termos específicos do domínio utilizados neste épico
      placeholder: |
        - **Pedido:** Definição clara em português
        - **Item:** Definição específica do contexto
        - **Status:** Definição dos estados possíveis
    validations:
      required: true
      
  - type: textarea
    id: business-value
    attributes:
      label: Valor de Negócio
      description: Por que este épico é importante para o negócio?
      placeholder: Descreva o valor e impacto esperado em português claro...
    validations:
      required: true
      
  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: Critérios em português claro para considerar este épico completo
      placeholder: |
        - [ ] DE: Modelagem tática completa
        - [ ] DE: Implementação domain + APIs
        - [ ] DBA: Review de schema
        - [ ] FE: UI components implementados
        - [ ] QAE: Testes E2E passando
        - [ ] PE: Deploy em produção
        - [ ] SEC: Security audit
        - [ ] SDA: Revisão Ubiquitous Language
      value: |
        - [ ] DE: Modelagem tática completa
        - [ ] DE: Implementação domain + APIs
        - [ ] DBA: Review de schema
        - [ ] FE: UI components implementados
        - [ ] QAE: Testes E2E passando
        - [ ] PE: Deploy em produção
        - [ ] SEC: Security audit
        - [ ] SDA: Revisão Ubiquitous Language
    validations:
      required: true
      
  - type: input
    id: timeline
    attributes:
      label: Timeline Estimado
      description: Qual a estimativa de sprints para este épico?
      placeholder: ex. Sprint 3-5 (6 semanas)
    validations:
      required: false
      
  - type: textarea
    id: dependencies
    attributes:
      label: Dependências
      description: Este épico depende de outros épicos ou componentes?
      placeholder: Liste outras issues, épicos ou requisitos técnicos
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        ## 📝 Comando para Revisão da Ubiquitous Language

        Ao completar o épico, execute o seguinte comando para revisar a linguagem ubíqua:

        ```
        SDA, revise e atualize a Ubiquitous Language considerando os novos termos descobertos no epic "[NOME-DO-EPIC]". Verifique deliverables: DE-XX, UXD-XX, FE-XX
        ```