name: 🏗️ Domain Modeling
description: Modelagem de domínio para um Bounded Context
title: "[DOMAIN] Modelar BC: "
labels: ["domain-modeling", "design", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🏗️ Template para Modelagem de Domínio
        Issue para modelar um Bounded Context completo usando DDD tactical patterns.
        
  - type: input
    id: bounded-context
    attributes:
      label: Bounded Context
      description: Nome do Bounded Context a ser modelado
      placeholder: ex. Sales, Inventory, Billing
    validations:
      required: true
      
  - type: input
    id: epic-link
    attributes:
      label: Épico Relacionado
      description: Link para o épico estratégico deste BC
      placeholder: "#123"
    validations:
      required: true
      
  - type: dropdown
    id: subdomain-type
    attributes:
      label: Tipo de Subdomínio
      description: Classificação do subdomínio deste BC
      options:
        - Core (Domínio Principal)
        - Supporting (Domínio de Suporte)  
        - Generic (Domínio Genérico)
    validations:
      required: true
      
  - type: textarea
    id: context-description
    attributes:
      label: Descrição do Contexto
      description: Visão geral do que este Bounded Context representa no negócio
      placeholder: Descreva em português o propósito e responsabilidades deste contexto...
    validations:
      required: true
      
  - type: textarea
    id: expected-aggregates
    attributes:
      label: Agregados Esperados
      description: Liste os possíveis agregados identificados na arquitetura
      placeholder: |
        - Order (Agregado Raiz)
        - Customer 
        - Product
    validations:
      required: false
      
  - type: textarea
    id: business-rules
    attributes:
      label: Regras de Negócio Identificadas
      description: Principais invariantes e regras de negócio conhecidas
      placeholder: |
        - Um pedido não pode ser cancelado após confirmação de pagamento
        - Cliente deve ter saldo suficiente para criar posição
    validations:
      required: false
      
  - type: textarea
    id: integration-needs
    attributes:
      label: Necessidades de Integração
      description: Com quais outros BCs ou sistemas externos precisa integrar?
      placeholder: APIs, eventos, mensageria necessária...
    validations:
      required: false
      
  - type: textarea
    id: deliverables
    attributes:
      label: Entregáveis Esperados
      description: Artefatos que devem ser gerados pelo DE
      value: |
        - [ ] `01-[ContextName]_Tactical_Model.md` - Modelo tático completo
        - [ ] `02-[ContextName]_Interfaces.cs` - Interfaces e contratos  
        - [ ] `03-[ContextName]_Use_Cases.md` - Casos de uso da aplicação
        - [ ] Atualização da Linguagem Ubíqua
    validations:
      required: false
      
  - type: input
    id: timeline
    attributes:
      label: Timeline
      description: Prazo estimado para conclusão
      placeholder: ex. 3-5 dias úteis
    validations:
      required: false