name: ⚙️ Technical Task
description: Tarefa técnica granular para implementação
title: "[TASK] "
labels: ["task", "technical", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ⚙️ Template para Tarefas Técnicas
        Issue para implementação técnica granular (subtarefa de uma feature).
        
  - type: input
    id: bounded-context
    attributes:
      label: Bounded Context
      description: BC ao qual esta tarefa pertence
      placeholder: ex. Sales, Inventory, Billing
    validations:
      required: true
      
  - type: dropdown
    id: task-type
    attributes:
      label: Tipo da Tarefa
      description: Qual tipo de implementação técnica?
      options:
        - 🏗️ Architecture Setup (SE)
        - 🎨 Frontend Component (FE)
        - 🔧 Backend API (BE) 
        - 🔍 Database Implementation (DBA)
        - 🧪 Testing Implementation (QAE)
        - 🚀 Infrastructure (PE)
        - 🔄 Integration Task
    validations:
      required: true
      
  - type: input
    id: feature-link
    attributes:
      label: Feature/User Story Relacionada
      description: Link para user story ou feature relacionada
      placeholder: "#156"
    validations:
      required: false
      
  - type: input
    id: domain-artifacts
    attributes:
      label: Artefatos de Referência
      description: Links para artefatos do DE/DBA que baseiam esta tarefa
      placeholder: "DE: #124, DBA: #125"
    validations:
      required: true
      
  - type: textarea
    id: task-description
    attributes:
      label: Descrição da Tarefa
      description: Descrição técnica detalhada do que deve ser implementado
      placeholder: |
        Implementar [componente/funcionalidade específica]:
        - Requisito técnico 1
        - Requisito técnico 2
        - Requisito técnico 3
    validations:
      required: true
      
  - type: textarea
    id: technical-specs
    attributes:
      label: Especificações Técnicas
      description: Detalhes técnicos, APIs, interfaces, padrões a seguir
      placeholder: |
        - Interface: IOrderRepository
        - Métodos: CreateOrder, UpdateOrder, GetOrder
        - Validações: Business rules aplicáveis
        - Testes: Unit tests necessários
    validations:
      required: true
      
  - type: dropdown
    id: complexity
    attributes:
      label: Complexidade
      description: Estimativa de complexidade desta tarefa
      options:
        - "🟢 Simple (1-2h)"
        - "🟡 Medium (0.5-1 dia)"
        - "🟠 Complex (1-3 dias)"
        - "🔴 Very Complex (3+ dias)"
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Prioridade de implementação
      options:
        - "🔴 High - Blocker para outros"
        - "🟡 Medium - Importante para sprint"
        - "🟢 Low - Pode ser postergado"
    validations:
      required: true
      
  - type: textarea
    id: dependencies
    attributes:
      label: Dependências
      description: Outras tarefas que devem ser concluídas primeiro
      placeholder: |
        - Aguarda: #123 (Setup inicial da arquitetura)
        - Aguarda: #124 (Database schema implementado)
    validations:
      required: false
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Critérios de Aceitação Técnicos
      description: Como validar que a tarefa foi concluída corretamente
      placeholder: |
        - [ ] Código implementado seguindo padrões DDD
        - [ ] Testes unitários escritos e passando
        - [ ] Code review aprovado
        - [ ] Integrado sem quebrar build
    validations:
      required: true
      
  - type: textarea
    id: testing-approach
    attributes:
      label: Abordagem de Testes
      description: Como esta implementação deve ser testada
      placeholder: |
        - Unit tests para regras de negócio
        - Integration tests para APIs
        - E2E tests se aplicável
    validations:
      required: false
      
  - type: input
    id: branch-name
    attributes:
      label: Nome da Branch Sugerido
      description: Seguindo Git Flow
      placeholder: "feature/sales-order-aggregate-#XXX"
    validations:
      required: false