name: 🐛 Bug Report  
description: Reportar um bug ou problema
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Obrigado por reportar o bug! Por favor, forneça o máximo de detalhes possível.
        
  - type: textarea
    id: bug-description
    attributes:
      label: Descrição do Bug
      description: Uma descrição clara e concisa do bug
      placeholder: Descreva o que aconteceu...
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Passos para Reproduzir
      description: Passos para reproduzir o comportamento
      placeholder: |
        1. Vá para '...'
        2. Clique em '....'
        3. Role para baixo até '....'
        4. Veja o erro
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamento Esperado
      description: Uma descrição clara do que você esperava que acontecesse
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Comportamento Atual
      description: Uma descrição clara do que realmente aconteceu
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severidade
      description: Qual o impacto deste bug?
      options:
        - "🔴 Critical - Sistema não funciona"
        - "🟡 High - Funcionalidade importante quebrada" 
        - "🟠 Medium - Funcionalidade menor quebrada"
        - "🟢 Low - Problema cosmético"
      default: 2
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: Em qual ambiente o bug foi encontrado?
      placeholder: |
        - OS: [ex. Windows 10, macOS]
        - Browser: [ex. Chrome 91, Firefox 89]
        - Versão: [ex. v1.0.0]
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Contexto Adicional
      description: Qualquer outra informação relevante sobre o problema
    validations:
      required: false