name: 🗄️ Database Design
description: Design de banco de dados para um Bounded Context
title: "[DATABASE] Schema BC: "
labels: ["database-design", "design", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🗄️ Template para Database Design
        Issue para projetar o schema completo de um Bounded Context.
        
  - type: input
    id: bounded-context
    attributes:
      label: Bounded Context
      description: Nome do Bounded Context para design do schema
      placeholder: ex. Sales, Inventory, Billing
    validations:
      required: true
      
  - type: input
    id: domain-issue
    attributes:
      label: Issue de Domain Modeling
      description: Link para a issue do DE que modela este BC
      placeholder: "#124"
    validations:
      required: true
      
  - type: input
    id: epic-link
    attributes:
      label: Épico Relacionado
      description: Link para o épico estratégico deste BC
      placeholder: "#123"
    validations:
      required: true
      
  - type: textarea
    id: expected-entities
    attributes:
      label: Entidades Esperadas
      description: Agregados e entidades identificados na arquitetura
      placeholder: |
        - Orders (aggregate root)
        - OrderItems
        - Customers
        - Products
    validations:
      required: false
      
  - type: dropdown
    id: database-type
    attributes:
      label: Tipo de Banco
      description: Qual tecnologia de banco será utilizada?
      options:
        - SQL Server
        - PostgreSQL
        - MySQL
        - MongoDB
        - A definir
      default: 4
    validations:
      required: true
      
  - type: textarea
    id: performance-requirements
    attributes:
      label: Requisitos de Performance
      description: Volumes esperados e requisitos de performance
      placeholder: |
        - Volume esperado de transações: X/dia
        - Tempo de resposta máximo: Xms
        - Consultas críticas identificadas
    validations:
      required: false
      
  - type: textarea
    id: integration-data
    attributes:
      label: Necessidades de Integração
      description: Dados compartilhados com outros BCs ou sistemas
      placeholder: Views, APIs de dados, sincronização necessária...
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Prioridade desta implementação
      options:
        - 🔴 High - Core Domain
        - 🟡 Medium - Supporting Domain  
        - 🟢 Low - Generic Domain
    validations:
      required: true
      
  - type: textarea
    id: security-requirements
    attributes:
      label: Requisitos de Segurança
      description: Dados sensíveis, compliance, criptografia necessária
      placeholder: |
        - Dados PII que precisam de criptografia
        - Requisitos LGPD/GDPR
        - Auditoria necessária
    validations:
      required: false
      
  - type: textarea
    id: deliverables
    attributes:
      label: Entregáveis Esperados
      description: Artefatos que devem ser gerados pelo DBA
      value: |
        - [ ] `01-[ContextName]_DB_Design.md` - Design completo do schema
        - [ ] `02-Indexing_Strategy.md` - Estratégia de indexação
        - [ ] `03-Security_Policy.md` - Políticas de segurança
        - [ ] `01-[ContextName]_DB_Schema.sql` - Scripts DDL
        - [ ] `02-Seed_Data.sql` - Dados iniciais
        - [ ] `[ContextName]_Migrations/` - Scripts de migração versionados
    validations:
      required: false
      
  - type: input
    id: timeline
    attributes:
      label: Timeline
      description: Prazo estimado para conclusão
      placeholder: ex. 2-4 dias úteis (após conclusão do DE)
    validations:
      required: false