# ==================================
# Traefik Static Configuration
# ==================================

# API and Dashboard
api:
  dashboard: true
  insecure: false  # Dashboard only via HTTPS

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

# Certificate Resolvers (Let's Encrypt)
certificatesResolvers:
  # Staging CA (for testing - no rate limits)
  letsencrypt-staging:
    acme:
      email: ${ACME_EMAIL}
      storage: /letsencrypt/acme-staging.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web

  # Production CA (trusted certificates)
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

# Docker Provider
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: mytrader-network

# Logging
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100

# Metrics (optional - for monitoring)
# metrics:
#   prometheus:
#     addEntryPointsLabels: true
#     addServicesLabels: true
