name: CD - Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://mytrader.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to Production
        run: |
          ./05-infra/scripts/deploy.sh production ${{ inputs.version }}

      - name: Notify success
        if: success()
        run: |
          echo "::notice::Deployment to production succeeded"
          echo "Frontend: https://mytrader.com"
          echo "API: https://api.mytrader.com"
          echo "Version: ${{ inputs.version }}"

      - name: Notify failure
        if: failure()
        run: echo "::error::Deployment to production failed"
